language: php

services:
  - docker

before_install:
  - docker build -t xorinzor/shoutz0r .
  - docker run -d -p 80:80 -p 443:443 --name shoutz0r xorinzor/shoutz0r

script:
  - docker exec -it shoutz0r /bin/sh -c "cd /usr/share/nginx/html/tests; phpunit"

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master