language: generic

services:
  - docker

before_install:
  - docker build -t xorinzor/shoutzor .
  - docker run -p 80:80 -p 8000:8000 xorinzor/shoutzor /bin/sh -c "cd /usr/share/nginx/html/tests/ && phpunit"

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
