trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: 8

resources:
  repositories:
    - repository: Shoutz0r
      type: github
      endpoint: github.com_xorinzor
      name: xorinzor/Shoutz0r

stages:

  - stage: unitTest
    jobs:
      - job: 'PHPUnit_Shoutz0rApp'
        displayName: 'Run PHPUnit for Shoutz0r-app'
        steps:
          - checkout: self
            persistCredentials: true
            clean: true

          - script: |
              cd ./Shoutz0r-app
              cp .env.template .env
            displayName: 'Environment Setup'

          - task: DockerCompose@0
            displayName: 'Start MySQL container in background'
            inputs:
              action: Run a Docker Compose command
              dockerComposeFile: docker-compose.yml
              additionalDockerComposeFiles: docker-compose.test.yml
              projectName: shoutzor
              dockerComposeCommand: up -d mysql

          - script: |
              sudo composer self-update
              composer install --no-interaction --prefer-dist --no-suggest
              composer --version
            displayName: 'Install Composer Packages'

          - script: |
              npm install
            displayName: 'Install NPM Packages'

          - script: |
              npm run production
            displayName: 'Build resource files with NPM & Webpack'

          - task: DockerCompose@0
            displayName: 'Run Shoutzor CLI Installer'
            inputs:
              action: Run a Docker Compose command
              dockerComposeFile: docker-compose.yml
              additionalDockerComposeFiles: docker-compose.test.yml
              projectName: shoutzor
              dockerComposeCommand: run php php /code/artisan shoutzor:install --useenv

          - script: |
              cp .env .env.testing
            displayName: 'Create testing .env file'

          - task: DockerCompose@0
            displayName: 'Rebuild config cache'
            inputs:
              action: Run a Docker Compose command
              dockerComposeFile: docker-compose.yml
              additionalDockerComposeFiles: docker-compose.test.yml
              projectName: shoutzor
              dockerComposeCommand: run php php /code/artisan config:cache

          - task: DockerCompose@0
            displayName: 'Run PHPUnit'
            inputs:
              action: Run a Docker Compose command
              dockerComposeFile: docker-compose.yml
              additionalDockerComposeFiles: docker-compose.test.yml
              projectName: shoutzor
              dockerComposeCommand: run phpunit

        #  - script: |
        #      php artisan key:generate --force
        #      php artisan passport:install --force
        #      php artisan migrate:fresh --force
        #      php artisan db:seed --force
        #    displayName: 'Running Migrations'

        #  - script: |
        #      vendor/bin/phpunit --log-junit tests/Results/TEST-phpunit-junit.xml
        #    displayName: 'Running Unit Tests'

        # Publish Test Results to Azure Pipelines/TFS
        #  - task: PublishTestResults@2
        #    inputs:
        #      testRunner: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit
        #      testResultsFiles: '**/TEST-*.xml'
        #      searchFolder: '$(System.DefaultWorkingDirectory)/tests/Results' # Optional
        #      mergeTestResults: false # Optional
        #      #testRunTitle: # Optional
        #      #buildPlatform: # Optional
        #      #buildConfiguration: # Optional
        #      #publishRunAttachments: true # Optional
        #    condition: always()
