version: '3.8'
services:
  web:
    image: 'nginx:latest'
    ports:
      - "80:80"
    volumes:
      - ./:/code:ro
      - ./site.conf.template:/etc/nginx/templates/site.conf.template:ro
    working_dir: /code
    networks:
      - shoutzor-frontend
    environment:
      - NGINX_HOST=shoutzor.local
      - NGINX_PORT=80

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-shoutzor.conf:ro
    working_dir: /code
    networks:
      - shoutzor-frontend
      - shoutzor-backend

  mysql:
    image: 'mysql:8'
    networks:
      - shoutzor-backend
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:?MYSQL_DB_NOT_PROVIDED}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:?MYSQL_PASSWORD_NOT_PROVIDED}

networks:
   shoutzor-frontend: {}
   shoutzor-backend: {}
