version: '3'
services:

  shoutzor:
    build: ./web/
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
      - "8888:8888"
    volumes:
      - ./web/www:/usr/share/nginx/html
      - ./node-app:/usr/src/app
      - ./node-app/node_modules:/usr/src/app/node_modules    

  db:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: changeme