version: '3.8'
services:
  web:
    image: 'nginx:latest'
    ports:
      - "80:80"
    volumes:
      - ./:/code:ro
      - ./site.conf.template:/etc/nginx/templates/site.conf.template:ro
    networks:
      - shoutzor-frontend
    environment:
      - NGINX_HOST=shoutzor.local
      - NGINX_PORT=80

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-shoutzor.conf:ro
    networks:
      - shoutzor-frontend
      - shoutzor-backend

  mysql:
    image: 'mysql:8'
    networks:
      - shoutzor-backend
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

networks:
   shoutzor-frontend: {}
   shoutzor-backend: {}
