version: '3.8'
services:
  web:
    image: 'nginx:latest'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/code:ro
      - ./site.conf.template:/etc/nginx/templates/site.conf.template:ro
    working_dir: /code
    networks:
      - shoutzor-frontend
    environment:
      - NGINX_HOST=shoutzor.local
      - NGINX_PORT=80

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-shoutzor.conf:ro
    working_dir: /code
    networks:
      - shoutzor-frontend
      - shoutzor-backend

  mysql:
    image: 'mysql:8'
    networks:
      - shoutzor-backend
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:?MYSQL_DB_NOT_PROVIDED}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:?MYSQL_PASSWORD_NOT_PROVIDED}

  echo:
    image: 'quay.io/soketi/soketi:1.1.0-16-debian'
    ports:
      - "6001:6001"
    networks:
      - shoutzor-backend
    environment:
      - SOKETI_DEBUG=${APP_DEBUG:-false}
      - SOKETI_SSL_CERT
      - SOKETI_SSL_KEY
      - SOKETI_SSL_PASS
      - SOKETI_DEFAULT_APP_ID=${PUSHER_APP_ID}
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET}

networks:
   shoutzor-frontend: {}
   shoutzor-backend: {}
