version: '3.8'
services:
  web:
    image: 'nginx:latest'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/code:ro
      - ./docker/site.conf.template:/etc/nginx/templates/site.conf.template:ro
    working_dir: /code
    networks:
      - shoutzor-frontend
    environment:
      - NGINX_HOST=shoutzor.local
      - NGINX_PORT=80
      - MAX_UPLOAD_SIZE=10M
      - FASTCGI_HOST=app
      - FASTCGI_PORT=9000

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    image: shoutz0r/app
    volumes:
      - ./:/code
      - ./docker/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-shoutzor.conf:ro
    working_dir: /code
    networks:
      - shoutzor-frontend
      - shoutzor-backend

  mysql:
    image: 'mysql:8'
    networks:
      - shoutzor-backend
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:?MYSQL_DB_NOT_PROVIDED}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:?MYSQL_PASSWORD_NOT_PROVIDED}

  queueWorker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    image: shoutz0r/worker
    depends_on:
      - mysql
    volumes:
      - ./:/code
      - ./docker/php-cli.conf:/usr/local/etc/php-cli.d/zzz-shoutzor.conf:ro
    working_dir: /code
    command: "php artisan queue:work --queue=uploads"
    networks:
      - shoutzor-backend

  redis:
    image: 'bitnami/redis:7.0'
    networks:
      - shoutzor-backend
    environment:
      - REDIS_PASSWORD
      - REDIS_TLS_ENABLED
      - REDIS_TLS_CERT_FILE
      - REDIS_TLS_KEY_FILE
      - REDIS_TLS_CA_FILE

  echo:
    image: 'quay.io/soketi/soketi:1.1.0-16-debian'
    ports:
      - "6001:6001"
    networks:
      - shoutzor-backend
    environment:
      - SOKETI_DEBUG=${APP_DEBUG:-false}
      - SOKETI_SSL_CERT
      - SOKETI_SSL_KEY
      - SOKETI_SSL_PASS
      - SOKETI_DEFAULT_APP_ID=${PUSHER_APP_ID}
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET}
      - SOKETI_DB_REDIS_HOST=${REDIS_HOST}
      - SOKETI_DB_REDIS_PORT=${REDIS_PORT}
      - SOKETI_DB_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SOKETI_DB_REDIS_DB=${REDIS_DB}
      - SOKETI_ADAPTER_DRIVER=redis
      - SOKETI_CACHE_DRIVER=memory
      - SOKETI_QUEUE_DRIVER=redis
      - SOKETI_DB_REDIS_KEY_PREFIX=soketi

networks:
  shoutzor-frontend: { }
  shoutzor-backend: { }
